FROM osrf/ros:jazzy-desktop-full

# install the basics
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 vim \
 tmux \
 cmake \
 gcc \
 g++ \
 git \
 build-essential \
 sudo \
 wget \
 curl \
 zip \
 unzip

# add a user
RUN userdel ubuntu
ARG user_id
ENV USER=dtc
RUN useradd -U --uid ${user_id} -ms /bin/bash $USER \
 && echo "$USER:$USER" | chpasswd \
 && adduser $USER sudo \
 && echo "$USER ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USER

# bagging
RUN apt install -y ros-jazzy-rosbag2-storage-mcap

# configure ros network
COPY ./zenoh.json5 /opt/zenoh.json5
COPY ./zenoh-router.json5 /opt/zenoh-router.json5
RUN apt install -y ros-jazzy-rmw-zenoh-cpp
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp
ENV ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
ENV ZENOH_CONFIG=/opt/zenoh.json5

# python util
RUN apt update \
 && apt install -y python3-pip \
 python3-venv \
 python3-pytest

# --- Install PyTAK from the .deb package ---
RUN wget https://github.com/snstac/pytak/releases/latest/download/pytak_latest_all.deb && \
    apt-get update && \
    apt-get install -y -f ./pytak_latest_all.deb && \
    rm ./pytak_latest_all.deb && \
    rm -rf /var/lib/apt/lists/*

# environment setup
USER $USER
WORKDIR /home/$USER
RUN mkdir -p ws/src

# Build workspace
WORKDIR /home/dtc/ws
RUN sudo rosdep init || true && rosdep update || true
RUN rosdep install --from-paths src --ignore-src -r -y
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && colcon build"

RUN sudo chown $USER:$USER ~/.bashrc \
 && /bin/sh -c 'echo ". /opt/ros/jazzy/setup.bash" >> ~/.bashrc' \
 && /bin/sh -c 'echo "source ~/ws/install/setup.bash" >> ~/.bashrc' \
 && echo 'export PS1="\[$(tput setaf 2; tput bold)\]\u\[$(tput setaf 7)\]@\[$(tput setaf 3)\]\h\[$(tput setaf 7)\]:\[$(tput setaf 4)\]\W\[$(tput setaf 7)\]$ \[$(tput sgr0)\]"' >> ~/.bashrc

